### ISSUE TITLE
channel.close() does not cause an exception on a waiting receiver

### ISSUE THREAD

**Issue by Ykulvaarlck** [rgalanakis/goless#54] opened 2021-02-04 14:59 UTC
```python
>>> from goless import *
>>> from gevent import *
>>> ch = chan()
>>> def foo():
	try:
		while True:
			r = ch.recv()
			print(r)
			if r == 'raise':
				raise Exception
			sleep(1)
	except:
		print('exception raised')

		
>>> go(foo)
>>> ch.send('hello')
hello
>>> ch.send('world')
world
>>> ch.send('raise')
raise
exception raised
>>> go(foo)
>>> ch.send('hello')
hello
>>> ch.close() # no printing of 'exception raised'
>>> ch.send('hello')
Traceback (most recent call last):
  File "<pyshell#158>", line 1, in <module>
    ch.send('hello')
  File "C:\Python38\lib\site-packages\goless\channels.py", line 36, in send
    raise ChannelClosed()
goless.channels.ChannelClosed
>>> ch = chan()
>>> ch.send('world') # receiver still receives from this new channel
world
```

**Comment by rgalanakis** [comment] 2021-02-05 07:43
Hi @Ykulvaarlck. I am not sure what you expect here:

> `>>> ch.close() # no printing of 'exception raised'`

Why are you expecting this to print here?

> `>>> ch.send('world') # receiver still receives from this new channel`

This is because you are overwriting the `ch` variable- the closure inside `foo` sees the new channel assigned to the `ch` variable and uses it. Again, I'm not sure what you expect here- `foo` is going to run continuously until it's garbage collected. It's not connected to the `ch` channel per se. Also I should note you actually have multiple routines reading from `ch`.

Perhaps try reproducing this without stomping on `ch`, which may be causing some confusion. Either pass in the channel the goroutine is supposed to use, create it in a closure, etc. Maybe there is a bug here (I know goless has bugs), but I cannot tell from the given example since it has its own set of problems.

I'm going to close this but I'm happy to get some feedback and reopen if you debug further.

**Closed by rgalanakis** 2021-02-05 07:43 UTC
